//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.10 at 12:26:33 PM WET 
//


package pt.quintans.mda.raw.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import pt.quintans.mda.core.ElementType;


/**
 * <p>Java class for AttributeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AttributeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="identity" type="{http://www.mda.quintans.pt}ent_identity" minOccurs="0"/>
 *         &lt;element name="version" type="{http://www.mda.quintans.pt}ent_version" minOccurs="0"/>
 *         &lt;element name="lov" type="{http://www.mda.quintans.pt}ent_lov" minOccurs="0"/>
 *         &lt;element name="string" type="{http://www.mda.quintans.pt}ent_string" minOccurs="0"/>
 *         &lt;element name="integer" type="{http://www.mda.quintans.pt}ent_integer" minOccurs="0"/>
 *         &lt;element name="long" type="{http://www.mda.quintans.pt}ent_long" minOccurs="0"/>
 *         &lt;element name="boolean" type="{http://www.mda.quintans.pt}ent_boolean" minOccurs="0"/>
 *         &lt;element name="decimal" type="{http://www.mda.quintans.pt}ent_decimal" minOccurs="0"/>
 *         &lt;element name="currency" type="{http://www.mda.quintans.pt}ent_currency" minOccurs="0"/>
 *         &lt;element name="timestamp" type="{http://www.mda.quintans.pt}ent_timestamp" minOccurs="0"/>
 *         &lt;element name="time" type="{http://www.mda.quintans.pt}ent_time" minOccurs="0"/>
 *         &lt;element name="date" type="{http://www.mda.quintans.pt}ent_date" minOccurs="0"/>
 *         &lt;element name="dateComposite" type="{http://www.mda.quintans.pt}ent_dateComposite" minOccurs="0"/>
 *         &lt;element name="flags" type="{http://www.mda.quintans.pt}ent_flags" minOccurs="0"/>
 *         &lt;element name="text" type="{http://www.mda.quintans.pt}ent_text" minOccurs="0"/>
 *         &lt;element name="bin" type="{http://www.mda.quintans.pt}ent_bin" minOccurs="0"/>
 *         &lt;element name="nested" type="{http://www.mda.quintans.pt}ent_nested" minOccurs="0"/>
 *         &lt;element name="point" type="{http://www.mda.quintans.pt}ent_point" minOccurs="0"/>
 *         &lt;element name="linestring" type="{http://www.mda.quintans.pt}ent_linestring" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AttributeType", propOrder = {
    "attributesList"
})
public class AttributeType
    extends ElementType
{

    @XmlElements({
        @XmlElement(name = "decimal", type = EntDecimal.class),
        @XmlElement(name = "string", type = EntString.class),
        @XmlElement(name = "version", type = EntVersion.class),
        @XmlElement(name = "flags", type = EntFlags.class),
        @XmlElement(name = "integer", type = EntInteger.class),
        @XmlElement(name = "long", type = EntLong.class),
        @XmlElement(name = "bin", type = EntBin.class),
        @XmlElement(name = "dateComposite", type = EntDateComposite.class),
        @XmlElement(name = "time", type = EntTime.class),
        @XmlElement(name = "linestring", type = EntLinestring.class),
        @XmlElement(name = "currency", type = EntCurrency.class),
        @XmlElement(name = "timestamp", type = EntTimestamp.class),
        @XmlElement(name = "date", type = EntDate.class),
        @XmlElement(name = "nested", type = EntNested.class),
        @XmlElement(name = "identity", type = EntIdentity.class),
        @XmlElement(name = "text", type = EntText.class),
        @XmlElement(name = "lov", type = EntLov.class),
        @XmlElement(name = "boolean", type = EntBoolean.class),
        @XmlElement(name = "point", type = EntPoint.class)
    })
    protected List<BaseAttributeType> attributesList;

    /**
     * Gets the value of the attributesList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributesList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributesList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntDecimal }
     * {@link EntString }
     * {@link EntVersion }
     * {@link EntFlags }
     * {@link EntInteger }
     * {@link EntLong }
     * {@link EntBin }
     * {@link EntDateComposite }
     * {@link EntTime }
     * {@link EntLinestring }
     * {@link EntCurrency }
     * {@link EntTimestamp }
     * {@link EntDate }
     * {@link EntNested }
     * {@link EntIdentity }
     * {@link EntText }
     * {@link EntLov }
     * {@link EntBoolean }
     * {@link EntPoint }
     * 
     * 
     */
    public List<BaseAttributeType> getAttributesList() {
        if (attributesList == null) {
            attributesList = new ArrayList<BaseAttributeType>();
        }
        return this.attributesList;
    }

}
