//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.10 at 12:26:33 PM WET 
//


package pt.quintans.mda.raw.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DaoOperationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DaoOperationType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.mda.quintans.pt}BaseType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="custom" type="{http://www.mda.quintans.pt}op_custom" minOccurs="0"/>
 *         &lt;element name="model" type="{http://www.mda.quintans.pt}op_model" minOccurs="0"/>
 *         &lt;element name="string" type="{http://www.mda.quintans.pt}op_string" minOccurs="0"/>
 *         &lt;element name="integer" type="{http://www.mda.quintans.pt}op_integer" minOccurs="0"/>
 *         &lt;element name="long" type="{http://www.mda.quintans.pt}op_long" minOccurs="0"/>
 *         &lt;element name="boolean" type="{http://www.mda.quintans.pt}op_boolean" minOccurs="0"/>
 *         &lt;element name="decimal" type="{http://www.mda.quintans.pt}op_decimal" minOccurs="0"/>
 *         &lt;element name="currency" type="{http://www.mda.quintans.pt}op_currency" minOccurs="0"/>
 *         &lt;element name="date" type="{http://www.mda.quintans.pt}op_date" minOccurs="0"/>
 *         &lt;element name="time" type="{http://www.mda.quintans.pt}op_time" minOccurs="0"/>
 *         &lt;element name="datetime" type="{http://www.mda.quintans.pt}op_datetime" minOccurs="0"/>
 *         &lt;element name="timestamp" type="{http://www.mda.quintans.pt}op_timestamp" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="single" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="paginate" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="roles" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="behaviors" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="transactional" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DaoOperationType", propOrder = {
    "attributesList"
})
public class DaoOperationType
    extends BaseType
{

    @XmlElements({
        @XmlElement(name = "time", type = OpTime.class),
        @XmlElement(name = "date", type = OpDate.class),
        @XmlElement(name = "custom", type = OpCustom.class),
        @XmlElement(name = "long", type = OpLong.class),
        @XmlElement(name = "boolean", type = OpBoolean.class),
        @XmlElement(name = "decimal", type = OpDecimal.class),
        @XmlElement(name = "timestamp", type = OpTimestamp.class),
        @XmlElement(name = "integer", type = OpInteger.class),
        @XmlElement(name = "datetime", type = OpDatetime.class),
        @XmlElement(name = "model", type = OpModel.class),
        @XmlElement(name = "string", type = OpString.class),
        @XmlElement(name = "currency", type = OpCurrency.class)
    })
    protected List<OpBaseAttributeType> attributesList;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String type;
    @XmlAttribute
    protected Boolean single;
    @XmlAttribute
    protected Boolean paginate;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String roles;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String behaviors;
    @XmlAttribute
    protected Boolean transactional;

    /**
     * Gets the value of the attributesList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributesList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributesList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OpTime }
     * {@link OpDate }
     * {@link OpCustom }
     * {@link OpLong }
     * {@link OpBoolean }
     * {@link OpDecimal }
     * {@link OpTimestamp }
     * {@link OpInteger }
     * {@link OpDatetime }
     * {@link OpModel }
     * {@link OpString }
     * {@link OpCurrency }
     * 
     * 
     */
    public List<OpBaseAttributeType> getAttributesList() {
        if (attributesList == null) {
            attributesList = new ArrayList<OpBaseAttributeType>();
        }
        return this.attributesList;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the single property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean getSingle() {
        if (single == null) {
            return true;
        } else {
            return single;
        }
    }

    /**
     * Sets the value of the single property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSingle(Boolean value) {
        this.single = value;
    }

    /**
     * Gets the value of the paginate property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean getPaginate() {
        if (paginate == null) {
            return false;
        } else {
            return paginate;
        }
    }

    /**
     * Sets the value of the paginate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPaginate(Boolean value) {
        this.paginate = value;
    }

    /**
     * Gets the value of the roles property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoles() {
        return roles;
    }

    /**
     * Sets the value of the roles property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoles(String value) {
        this.roles = value;
    }

    /**
     * Gets the value of the behaviors property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBehaviors() {
        return behaviors;
    }

    /**
     * Sets the value of the behaviors property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBehaviors(String value) {
        this.behaviors = value;
    }

    /**
     * Gets the value of the transactional property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean getTransactional() {
        if (transactional == null) {
            return false;
        } else {
            return transactional;
        }
    }

    /**
     * Sets the value of the transactional property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTransactional(Boolean value) {
        this.transactional = value;
    }

}
