//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.10 at 12:26:33 PM WET 
//


package pt.quintans.mda.raw.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import pt.quintans.mda.core.ElementType;


/**
 * <p>Java class for DtoAttributeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DtoAttributeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="lov" type="{http://www.mda.quintans.pt}dto_lov" minOccurs="0"/>
 *         &lt;element name="string" type="{http://www.mda.quintans.pt}dto_string" minOccurs="0"/>
 *         &lt;element name="integer" type="{http://www.mda.quintans.pt}dto_integer" minOccurs="0"/>
 *         &lt;element name="long" type="{http://www.mda.quintans.pt}dto_long" minOccurs="0"/>
 *         &lt;element name="boolean" type="{http://www.mda.quintans.pt}dto_boolean" minOccurs="0"/>
 *         &lt;element name="decimal" type="{http://www.mda.quintans.pt}dto_decimal" minOccurs="0"/>
 *         &lt;element name="currency" type="{http://www.mda.quintans.pt}dto_currency" minOccurs="0"/>
 *         &lt;element name="date" type="{http://www.mda.quintans.pt}dto_date" minOccurs="0"/>
 *         &lt;element name="time" type="{http://www.mda.quintans.pt}dto_time" minOccurs="0"/>
 *         &lt;element name="datetime" type="{http://www.mda.quintans.pt}dto_datetime" minOccurs="0"/>
 *         &lt;element name="timestamp" type="{http://www.mda.quintans.pt}dto_timestamp" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DtoAttributeType", propOrder = {
    "attributesList"
})
public class DtoAttributeType
    extends ElementType
{

    @XmlElements({
        @XmlElement(name = "integer", type = DtoInteger.class),
        @XmlElement(name = "currency", type = DtoCurrency.class),
        @XmlElement(name = "long", type = DtoLong.class),
        @XmlElement(name = "datetime", type = DtoDatetime.class),
        @XmlElement(name = "lov", type = DtoLov.class),
        @XmlElement(name = "string", type = DtoString.class),
        @XmlElement(name = "decimal", type = DtoDecimal.class),
        @XmlElement(name = "boolean", type = DtoBoolean.class),
        @XmlElement(name = "timestamp", type = DtoTimestamp.class),
        @XmlElement(name = "date", type = DtoDate.class),
        @XmlElement(name = "time", type = DtoTime.class)
    })
    protected List<AttrBaseAttributeType> attributesList;

    /**
     * Gets the value of the attributesList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributesList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributesList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DtoInteger }
     * {@link DtoCurrency }
     * {@link DtoLong }
     * {@link DtoDatetime }
     * {@link DtoLov }
     * {@link DtoString }
     * {@link DtoDecimal }
     * {@link DtoBoolean }
     * {@link DtoTimestamp }
     * {@link DtoDate }
     * {@link DtoTime }
     * 
     * 
     */
    public List<AttrBaseAttributeType> getAttributesList() {
        if (attributesList == null) {
            attributesList = new ArrayList<AttrBaseAttributeType>();
        }
        return this.attributesList;
    }

}
