//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.10 at 12:26:33 PM WET 
//


package pt.quintans.mda.raw.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ent_dateComposite complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ent_dateComposite">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.mda.quintans.pt}BaseAttributeType">
 *       &lt;sequence>
 *         &lt;element name="day" type="{http://www.mda.quintans.pt}ent_integer" minOccurs="0"/>
 *         &lt;element name="month" type="{http://www.mda.quintans.pt}ent_integer" minOccurs="0"/>
 *         &lt;element name="year" type="{http://www.mda.quintans.pt}ent_integer"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ent_dateComposite", propOrder = {
    "day",
    "month",
    "year"
})
public class EntDateComposite
    extends BaseAttributeType
{

    protected EntInteger day;
    protected EntInteger month;
    @XmlElement(required = true)
    protected EntInteger year;

    /**
     * Gets the value of the day property.
     * 
     * @return
     *     possible object is
     *     {@link EntInteger }
     *     
     */
    public EntInteger getDay() {
        return day;
    }

    /**
     * Sets the value of the day property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntInteger }
     *     
     */
    public void setDay(EntInteger value) {
        this.day = value;
    }

    /**
     * Gets the value of the month property.
     * 
     * @return
     *     possible object is
     *     {@link EntInteger }
     *     
     */
    public EntInteger getMonth() {
        return month;
    }

    /**
     * Sets the value of the month property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntInteger }
     *     
     */
    public void setMonth(EntInteger value) {
        this.month = value;
    }

    /**
     * Gets the value of the year property.
     * 
     * @return
     *     possible object is
     *     {@link EntInteger }
     *     
     */
    public EntInteger getYear() {
        return year;
    }

    /**
     * Sets the value of the year property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntInteger }
     *     
     */
    public void setYear(EntInteger value) {
        this.year = value;
    }

}
