//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.10 at 12:26:33 PM WET 
//


package pt.quintans.mda.raw.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ent_flags complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ent_flags">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.mda.quintans.pt}BaseAttributeType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="lov" type="{http://www.mda.quintans.pt}flags_lov" minOccurs="0"/>
 *         &lt;element name="bool" type="{http://www.mda.quintans.pt}flags_bool" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ent_flags", propOrder = {
    "flagList"
})
public class EntFlags
    extends BaseAttributeType
{

    @XmlElements({
        @XmlElement(name = "bool", type = FlagsBool.class),
        @XmlElement(name = "lov", type = FlagsLov.class)
    })
    protected List<BaseAttributeType> flagList;

    /**
     * Gets the value of the flagList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the flagList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFlagList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FlagsBool }
     * {@link FlagsLov }
     * 
     * 
     */
    public List<BaseAttributeType> getFlagList() {
        if (flagList == null) {
            flagList = new ArrayList<BaseAttributeType>();
        }
        return this.flagList;
    }

}
