//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.10 at 12:26:33 PM WET 
//


package pt.quintans.mda.raw.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.mda.quintans.pt}basic">
 *       &lt;sequence>
 *         &lt;element name="attributes" type="{http://www.mda.quintans.pt}AttributeType"/>
 *         &lt;element name="associations" type="{http://www.mda.quintans.pt}AssociationType" minOccurs="0"/>
 *         &lt;element name="index" type="{http://www.mda.quintans.pt}IndexType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="uniqueGroup" type="{http://www.mda.quintans.pt}UniqueGroupType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="references" type="{http://www.mda.quintans.pt}ReferencesType" minOccurs="0"/>
 *         &lt;element name="dao" type="{http://www.mda.quintans.pt}DaoType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="readonly" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="nested" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="exposedToRoles" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="writingRoles" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "attributes",
    "associations",
    "index",
    "uniqueGroup",
    "references",
    "dao"
})
@XmlRootElement(name = "entity")
public class Entity
    extends Basic
{

    @XmlElement(required = true)
    protected AttributeType attributes;
    protected AssociationType associations;
    protected List<IndexType> index;
    protected List<UniqueGroupType> uniqueGroup;
    protected ReferencesType references;
    protected DaoType dao;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String id;
    @XmlAttribute
    protected Boolean readonly;
    @XmlAttribute
    protected Boolean nested;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String exposedToRoles;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String writingRoles;

    /**
     * Gets the value of the attributes property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeType }
     *     
     */
    public AttributeType getAttributes() {
        return attributes;
    }

    /**
     * Sets the value of the attributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeType }
     *     
     */
    public void setAttributes(AttributeType value) {
        this.attributes = value;
    }

    /**
     * Gets the value of the associations property.
     * 
     * @return
     *     possible object is
     *     {@link AssociationType }
     *     
     */
    public AssociationType getAssociations() {
        return associations;
    }

    /**
     * Sets the value of the associations property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssociationType }
     *     
     */
    public void setAssociations(AssociationType value) {
        this.associations = value;
    }

    /**
     * Gets the value of the index property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the index property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIndex().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IndexType }
     * 
     * 
     */
    public List<IndexType> getIndex() {
        if (index == null) {
            index = new ArrayList<IndexType>();
        }
        return this.index;
    }

    /**
     * Gets the value of the uniqueGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the uniqueGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUniqueGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UniqueGroupType }
     * 
     * 
     */
    public List<UniqueGroupType> getUniqueGroup() {
        if (uniqueGroup == null) {
            uniqueGroup = new ArrayList<UniqueGroupType>();
        }
        return this.uniqueGroup;
    }

    /**
     * Gets the value of the references property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencesType }
     *     
     */
    public ReferencesType getReferences() {
        return references;
    }

    /**
     * Sets the value of the references property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencesType }
     *     
     */
    public void setReferences(ReferencesType value) {
        this.references = value;
    }

    /**
     * Gets the value of the dao property.
     * 
     * @return
     *     possible object is
     *     {@link DaoType }
     *     
     */
    public DaoType getDao() {
        return dao;
    }

    /**
     * Sets the value of the dao property.
     * 
     * @param value
     *     allowed object is
     *     {@link DaoType }
     *     
     */
    public void setDao(DaoType value) {
        this.dao = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the readonly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean getReadonly() {
        if (readonly == null) {
            return false;
        } else {
            return readonly;
        }
    }

    /**
     * Sets the value of the readonly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReadonly(Boolean value) {
        this.readonly = value;
    }

    /**
     * Gets the value of the nested property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean getNested() {
        if (nested == null) {
            return false;
        } else {
            return nested;
        }
    }

    /**
     * Sets the value of the nested property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNested(Boolean value) {
        this.nested = value;
    }

    /**
     * Gets the value of the exposedToRoles property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExposedToRoles() {
        return exposedToRoles;
    }

    /**
     * Sets the value of the exposedToRoles property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExposedToRoles(String value) {
        this.exposedToRoles = value;
    }

    /**
     * Gets the value of the writingRoles property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWritingRoles() {
        return writingRoles;
    }

    /**
     * Sets the value of the writingRoles property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWritingRoles(String value) {
        this.writingRoles = value;
    }

}
