//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.10 at 12:26:33 PM WET 
//


package pt.quintans.mda.raw.domain;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pt.quintans.mda.raw.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pt.quintans.mda.raw.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Constants }
     * 
     */
    public Constants createConstants() {
        return new Constants();
    }

    /**
     * Create an instance of {@link SrvDecimal }
     * 
     */
    public SrvDecimal createSrvDecimal() {
        return new SrvDecimal();
    }

    /**
     * Create an instance of {@link AttributeType }
     * 
     */
    public AttributeType createAttributeType() {
        return new AttributeType();
    }

    /**
     * Create an instance of {@link BaseAttributeType }
     * 
     */
    public BaseAttributeType createBaseAttributeType() {
        return new BaseAttributeType();
    }

    /**
     * Create an instance of {@link RelationType }
     * 
     */
    public RelationType createRelationType() {
        return new RelationType();
    }

    /**
     * Create an instance of {@link ViewSection }
     * 
     */
    public ViewSection createViewSection() {
        return new ViewSection();
    }

    /**
     * Create an instance of {@link IndexMemberType }
     * 
     */
    public IndexMemberType createIndexMemberType() {
        return new IndexMemberType();
    }

    /**
     * Create an instance of {@link DtoBoolean }
     * 
     */
    public DtoBoolean createDtoBoolean() {
        return new DtoBoolean();
    }

    /**
     * Create an instance of {@link Constant }
     * 
     */
    public Constant createConstant() {
        return new Constant();
    }

    /**
     * Create an instance of {@link EntCurrency }
     * 
     */
    public EntCurrency createEntCurrency() {
        return new EntCurrency();
    }

    /**
     * Create an instance of {@link OpTimestamp }
     * 
     */
    public OpTimestamp createOpTimestamp() {
        return new OpTimestamp();
    }

    /**
     * Create an instance of {@link EntDate }
     * 
     */
    public EntDate createEntDate() {
        return new EntDate();
    }

    /**
     * Create an instance of {@link DtoTimestamp }
     * 
     */
    public DtoTimestamp createDtoTimestamp() {
        return new DtoTimestamp();
    }

    /**
     * Create an instance of {@link OpDecimal }
     * 
     */
    public OpDecimal createOpDecimal() {
        return new OpDecimal();
    }

    /**
     * Create an instance of {@link FlagsBool }
     * 
     */
    public FlagsBool createFlagsBool() {
        return new FlagsBool();
    }

    /**
     * Create an instance of {@link Screen.Display }
     * 
     */
    public Screen.Display createScreenDisplay() {
        return new Screen.Display();
    }

    /**
     * Create an instance of {@link OperationsType }
     * 
     */
    public OperationsType createOperationsType() {
        return new OperationsType();
    }

    /**
     * Create an instance of {@link BaseType }
     * 
     */
    public BaseType createBaseType() {
        return new BaseType();
    }

    /**
     * Create an instance of {@link EntLov }
     * 
     */
    public EntLov createEntLov() {
        return new EntLov();
    }

    /**
     * Create an instance of {@link Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link IndexType }
     * 
     */
    public IndexType createIndexType() {
        return new IndexType();
    }

    /**
     * Create an instance of {@link EntNested }
     * 
     */
    public EntNested createEntNested() {
        return new EntNested();
    }

    /**
     * Create an instance of {@link EntString }
     * 
     */
    public EntString createEntString() {
        return new EntString();
    }

    /**
     * Create an instance of {@link OpModel }
     * 
     */
    public OpModel createOpModel() {
        return new OpModel();
    }

    /**
     * Create an instance of {@link UniqueGroupMemberType }
     * 
     */
    public UniqueGroupMemberType createUniqueGroupMemberType() {
        return new UniqueGroupMemberType();
    }

    /**
     * Create an instance of {@link FlagsLov }
     * 
     */
    public FlagsLov createFlagsLov() {
        return new FlagsLov();
    }

    /**
     * Create an instance of {@link FieldType }
     * 
     */
    public FieldType createFieldType() {
        return new FieldType();
    }

    /**
     * Create an instance of {@link ListOfValues }
     * 
     */
    public ListOfValues createListOfValues() {
        return new ListOfValues();
    }

    /**
     * Create an instance of {@link SrvDate }
     * 
     */
    public SrvDate createSrvDate() {
        return new SrvDate();
    }

    /**
     * Create an instance of {@link HasManyType }
     * 
     */
    public HasManyType createHasManyType() {
        return new HasManyType();
    }

    /**
     * Create an instance of {@link UniqueGroupType }
     * 
     */
    public UniqueGroupType createUniqueGroupType() {
        return new UniqueGroupType();
    }

    /**
     * Create an instance of {@link AttrCustom }
     * 
     */
    public AttrCustom createAttrCustom() {
        return new AttrCustom();
    }

    /**
     * Create an instance of {@link DaoType }
     * 
     */
    public DaoType createDaoType() {
        return new DaoType();
    }

    /**
     * Create an instance of {@link Entity }
     * 
     */
    public Entity createEntity() {
        return new Entity();
    }

    /**
     * Create an instance of {@link EntVersion }
     * 
     */
    public EntVersion createEntVersion() {
        return new EntVersion();
    }

    /**
     * Create an instance of {@link SrvBinary }
     * 
     */
    public SrvBinary createSrvBinary() {
        return new SrvBinary();
    }

    /**
     * Create an instance of {@link HasOneType }
     * 
     */
    public HasOneType createHasOneType() {
        return new HasOneType();
    }

    /**
     * Create an instance of {@link EntLong }
     * 
     */
    public EntLong createEntLong() {
        return new EntLong();
    }

    /**
     * Create an instance of {@link DtoDatetime }
     * 
     */
    public DtoDatetime createDtoDatetime() {
        return new DtoDatetime();
    }

    /**
     * Create an instance of {@link DtoAttributeType }
     * 
     */
    public DtoAttributeType createDtoAttributeType() {
        return new DtoAttributeType();
    }

    /**
     * Create an instance of {@link DtoDate }
     * 
     */
    public DtoDate createDtoDate() {
        return new DtoDate();
    }

    /**
     * Create an instance of {@link SrvByte }
     * 
     */
    public SrvByte createSrvByte() {
        return new SrvByte();
    }

    /**
     * Create an instance of {@link GisAttributeType }
     * 
     */
    public GisAttributeType createGisAttributeType() {
        return new GisAttributeType();
    }

    /**
     * Create an instance of {@link EntIdentity }
     * 
     */
    public EntIdentity createEntIdentity() {
        return new EntIdentity();
    }

    /**
     * Create an instance of {@link SrvBoolean }
     * 
     */
    public SrvBoolean createSrvBoolean() {
        return new SrvBoolean();
    }

    /**
     * Create an instance of {@link EntDateComposite }
     * 
     */
    public EntDateComposite createEntDateComposite() {
        return new EntDateComposite();
    }

    /**
     * Create an instance of {@link Role }
     * 
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link DtoCurrency }
     * 
     */
    public DtoCurrency createDtoCurrency() {
        return new DtoCurrency();
    }

    /**
     * Create an instance of {@link DtoTime }
     * 
     */
    public DtoTime createDtoTime() {
        return new DtoTime();
    }

    /**
     * Create an instance of {@link SrvString }
     * 
     */
    public SrvString createSrvString() {
        return new SrvString();
    }

    /**
     * Create an instance of {@link DtoDecimal }
     * 
     */
    public DtoDecimal createDtoDecimal() {
        return new DtoDecimal();
    }

    /**
     * Create an instance of {@link DaoOperationType }
     * 
     */
    public DaoOperationType createDaoOperationType() {
        return new DaoOperationType();
    }

    /**
     * Create an instance of {@link EntDecimal }
     * 
     */
    public EntDecimal createEntDecimal() {
        return new EntDecimal();
    }

    /**
     * Create an instance of {@link EntBoolean }
     * 
     */
    public EntBoolean createEntBoolean() {
        return new EntBoolean();
    }

    /**
     * Create an instance of {@link OpBaseAttributeType }
     * 
     */
    public OpBaseAttributeType createOpBaseAttributeType() {
        return new OpBaseAttributeType();
    }

    /**
     * Create an instance of {@link AttrModel }
     * 
     */
    public AttrModel createAttrModel() {
        return new AttrModel();
    }

    /**
     * Create an instance of {@link ReferenceType }
     * 
     */
    public ReferenceType createReferenceType() {
        return new ReferenceType();
    }

    /**
     * Create an instance of {@link SrvInteger }
     * 
     */
    public SrvInteger createSrvInteger() {
        return new SrvInteger();
    }

    /**
     * Create an instance of {@link ChainType }
     * 
     */
    public ChainType createChainType() {
        return new ChainType();
    }

    /**
     * Create an instance of {@link ReferencesType }
     * 
     */
    public ReferencesType createReferencesType() {
        return new ReferencesType();
    }

    /**
     * Create an instance of {@link Screen }
     * 
     */
    public Screen createScreen() {
        return new Screen();
    }

    /**
     * Create an instance of {@link DtoInteger }
     * 
     */
    public DtoInteger createDtoInteger() {
        return new DtoInteger();
    }

    /**
     * Create an instance of {@link OpTime }
     * 
     */
    public OpTime createOpTime() {
        return new OpTime();
    }

    /**
     * Create an instance of {@link ViewType }
     * 
     */
    public ViewType createViewType() {
        return new ViewType();
    }

    /**
     * Create an instance of {@link OpBoolean }
     * 
     */
    public OpBoolean createOpBoolean() {
        return new OpBoolean();
    }

    /**
     * Create an instance of {@link BaseAssociationType }
     * 
     */
    public BaseAssociationType createBaseAssociationType() {
        return new BaseAssociationType();
    }

    /**
     * Create an instance of {@link Dto }
     * 
     */
    public Dto createDto() {
        return new Dto();
    }

    /**
     * Create an instance of {@link DtoLong }
     * 
     */
    public DtoLong createDtoLong() {
        return new DtoLong();
    }

    /**
     * Create an instance of {@link NavigationType }
     * 
     */
    public NavigationType createNavigationType() {
        return new NavigationType();
    }

    /**
     * Create an instance of {@link SrvLong }
     * 
     */
    public SrvLong createSrvLong() {
        return new SrvLong();
    }

    /**
     * Create an instance of {@link EntTimestamp }
     * 
     */
    public EntTimestamp createEntTimestamp() {
        return new EntTimestamp();
    }

    /**
     * Create an instance of {@link ItemType }
     * 
     */
    public ItemType createItemType() {
        return new ItemType();
    }

    /**
     * Create an instance of {@link OrderType }
     * 
     */
    public OrderType createOrderType() {
        return new OrderType();
    }

    /**
     * Create an instance of {@link DtoLov }
     * 
     */
    public DtoLov createDtoLov() {
        return new DtoLov();
    }

    /**
     * Create an instance of {@link OpDate }
     * 
     */
    public OpDate createOpDate() {
        return new OpDate();
    }

    /**
     * Create an instance of {@link OpCurrency }
     * 
     */
    public OpCurrency createOpCurrency() {
        return new OpCurrency();
    }

    /**
     * Create an instance of {@link EntFlags }
     * 
     */
    public EntFlags createEntFlags() {
        return new EntFlags();
    }

    /**
     * Create an instance of {@link EntInteger }
     * 
     */
    public EntInteger createEntInteger() {
        return new EntInteger();
    }

    /**
     * Create an instance of {@link AssociationType }
     * 
     */
    public AssociationType createAssociationType() {
        return new AssociationType();
    }

    /**
     * Create an instance of {@link SimpleAssociationType }
     * 
     */
    public SimpleAssociationType createSimpleAssociationType() {
        return new SimpleAssociationType();
    }

    /**
     * Create an instance of {@link ConstraintType }
     * 
     */
    public ConstraintType createConstraintType() {
        return new ConstraintType();
    }

    /**
     * Create an instance of {@link Screen.Head }
     * 
     */
    public Screen.Head createScreenHead() {
        return new Screen.Head();
    }

    /**
     * Create an instance of {@link OrdersType }
     * 
     */
    public OrdersType createOrdersType() {
        return new OrdersType();
    }

    /**
     * Create an instance of {@link OpLong }
     * 
     */
    public OpLong createOpLong() {
        return new OpLong();
    }

    /**
     * Create an instance of {@link EntText }
     * 
     */
    public EntText createEntText() {
        return new EntText();
    }

    /**
     * Create an instance of {@link EntPoint }
     * 
     */
    public EntPoint createEntPoint() {
        return new EntPoint();
    }

    /**
     * Create an instance of {@link NavigationsType }
     * 
     */
    public NavigationsType createNavigationsType() {
        return new NavigationsType();
    }

    /**
     * Create an instance of {@link DtoString }
     * 
     */
    public DtoString createDtoString() {
        return new DtoString();
    }

    /**
     * Create an instance of {@link AttrBaseAttributeType }
     * 
     */
    public AttrBaseAttributeType createAttrBaseAttributeType() {
        return new AttrBaseAttributeType();
    }

    /**
     * Create an instance of {@link OpDatetime }
     * 
     */
    public OpDatetime createOpDatetime() {
        return new OpDatetime();
    }

    /**
     * Create an instance of {@link EntTime }
     * 
     */
    public EntTime createEntTime() {
        return new EntTime();
    }

    /**
     * Create an instance of {@link EntBin }
     * 
     */
    public EntBin createEntBin() {
        return new EntBin();
    }

    /**
     * Create an instance of {@link OperationType }
     * 
     */
    public OperationType createOperationType() {
        return new OperationType();
    }

    /**
     * Create an instance of {@link OpCustom }
     * 
     */
    public OpCustom createOpCustom() {
        return new OpCustom();
    }

    /**
     * Create an instance of {@link OpString }
     * 
     */
    public OpString createOpString() {
        return new OpString();
    }

    /**
     * Create an instance of {@link EntLinestring }
     * 
     */
    public EntLinestring createEntLinestring() {
        return new EntLinestring();
    }

    /**
     * Create an instance of {@link Screen.Result }
     * 
     */
    public Screen.Result createScreenResult() {
        return new Screen.Result();
    }

    /**
     * Create an instance of {@link Basic }
     * 
     */
    public Basic createBasic() {
        return new Basic();
    }

    /**
     * Create an instance of {@link OpInteger }
     * 
     */
    public OpInteger createOpInteger() {
        return new OpInteger();
    }

}
