//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.10 at 12:26:33 PM WET 
//


package pt.quintans.mda.raw.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OperationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OperationType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.mda.quintans.pt}BaseType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="custom" type="{http://www.mda.quintans.pt}attr_custom" minOccurs="0"/>
 *         &lt;element name="model" type="{http://www.mda.quintans.pt}attr_model" minOccurs="0"/>
 *         &lt;element name="string" type="{http://www.mda.quintans.pt}srv_string" minOccurs="0"/>
 *         &lt;element name="integer" type="{http://www.mda.quintans.pt}srv_integer" minOccurs="0"/>
 *         &lt;element name="long" type="{http://www.mda.quintans.pt}srv_long" minOccurs="0"/>
 *         &lt;element name="boolean" type="{http://www.mda.quintans.pt}srv_boolean" minOccurs="0"/>
 *         &lt;element name="decimal" type="{http://www.mda.quintans.pt}srv_decimal" minOccurs="0"/>
 *         &lt;element name="date" type="{http://www.mda.quintans.pt}srv_date" minOccurs="0"/>
 *         &lt;element name="byte" type="{http://www.mda.quintans.pt}srv_byte" minOccurs="0"/>
 *         &lt;element name="binary" type="{http://www.mda.quintans.pt}srv_binary" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="roles" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="single" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="paginate" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="behaviors" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="transactional" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="internal" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="scheduled" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OperationType", propOrder = {
    "attributesList"
})
public class OperationType
    extends BaseType
{

    @XmlElements({
        @XmlElement(name = "long", type = SrvLong.class),
        @XmlElement(name = "custom", type = AttrCustom.class),
        @XmlElement(name = "model", type = AttrModel.class),
        @XmlElement(name = "string", type = SrvString.class),
        @XmlElement(name = "boolean", type = SrvBoolean.class),
        @XmlElement(name = "integer", type = SrvInteger.class),
        @XmlElement(name = "decimal", type = SrvDecimal.class),
        @XmlElement(name = "date", type = SrvDate.class),
        @XmlElement(name = "binary", type = SrvBinary.class),
        @XmlElement(name = "byte", type = SrvByte.class)
    })
    protected List<AttrBaseAttributeType> attributesList;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String roles;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String type;
    @XmlAttribute
    protected Boolean single;
    @XmlAttribute
    protected Boolean paginate;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String behaviors;
    @XmlAttribute
    protected Boolean transactional;
    @XmlAttribute
    protected Boolean internal;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String scheduled;

    /**
     * Gets the value of the attributesList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributesList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributesList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SrvLong }
     * {@link AttrCustom }
     * {@link AttrModel }
     * {@link SrvString }
     * {@link SrvBoolean }
     * {@link SrvInteger }
     * {@link SrvDecimal }
     * {@link SrvDate }
     * {@link SrvBinary }
     * {@link SrvByte }
     * 
     * 
     */
    public List<AttrBaseAttributeType> getAttributesList() {
        if (attributesList == null) {
            attributesList = new ArrayList<AttrBaseAttributeType>();
        }
        return this.attributesList;
    }

    /**
     * Gets the value of the roles property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoles() {
        return roles;
    }

    /**
     * Sets the value of the roles property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoles(String value) {
        this.roles = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the single property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean getSingle() {
        if (single == null) {
            return true;
        } else {
            return single;
        }
    }

    /**
     * Sets the value of the single property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSingle(Boolean value) {
        this.single = value;
    }

    /**
     * Gets the value of the paginate property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean getPaginate() {
        if (paginate == null) {
            return false;
        } else {
            return paginate;
        }
    }

    /**
     * Sets the value of the paginate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPaginate(Boolean value) {
        this.paginate = value;
    }

    /**
     * Gets the value of the behaviors property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBehaviors() {
        return behaviors;
    }

    /**
     * Sets the value of the behaviors property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBehaviors(String value) {
        this.behaviors = value;
    }

    /**
     * Gets the value of the transactional property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean getTransactional() {
        if (transactional == null) {
            return false;
        } else {
            return transactional;
        }
    }

    /**
     * Sets the value of the transactional property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTransactional(Boolean value) {
        this.transactional = value;
    }

    /**
     * Gets the value of the internal property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getInternal() {
        return internal;
    }

    /**
     * Sets the value of the internal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInternal(Boolean value) {
        this.internal = value;
    }

    /**
     * Gets the value of the scheduled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScheduled() {
        return scheduled;
    }

    /**
     * Sets the value of the scheduled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScheduled(String value) {
        this.scheduled = value;
    }

}
