//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.10 at 12:26:33 PM WET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.mda.quintans.pt", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pt.quintans.mda.raw.domain;
