//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.10 at 12:26:33 PM WET 
//


package pt.quintans.mda.raw.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.mda.quintans.pt}basic">
 *       &lt;sequence>
 *         &lt;element name="head" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.mda.quintans.pt}viewSection">
 *                 &lt;attribute name="target" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="search" type="{http://www.mda.quintans.pt}viewSection" minOccurs="0"/>
 *         &lt;element name="orders" type="{http://www.mda.quintans.pt}ordersType" minOccurs="0"/>
 *         &lt;element name="result" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.mda.quintans.pt}viewSection">
 *                 &lt;attribute name="pageSize" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="selectable" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                 &lt;attribute name="sortable" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="display" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.mda.quintans.pt}viewSection">
 *                 &lt;attribute name="embeded" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="navigations" type="{http://www.mda.quintans.pt}navigationsType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="entity" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="example" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="softDelete" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="canDelete" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="canSave" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "head",
    "search",
    "orders",
    "result",
    "display",
    "navigations"
})
@XmlRootElement(name = "screen")
public class Screen
    extends Basic
{

    protected Screen.Head head;
    protected ViewSection search;
    protected OrdersType orders;
    protected Screen.Result result;
    protected Screen.Display display;
    protected NavigationsType navigations;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String entity;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String example;
    @XmlAttribute
    protected Boolean softDelete;
    @XmlAttribute
    protected Boolean canDelete;
    @XmlAttribute
    protected Boolean canSave;

    /**
     * Gets the value of the head property.
     * 
     * @return
     *     possible object is
     *     {@link Screen.Head }
     *     
     */
    public Screen.Head getHead() {
        return head;
    }

    /**
     * Sets the value of the head property.
     * 
     * @param value
     *     allowed object is
     *     {@link Screen.Head }
     *     
     */
    public void setHead(Screen.Head value) {
        this.head = value;
    }

    /**
     * Gets the value of the search property.
     * 
     * @return
     *     possible object is
     *     {@link ViewSection }
     *     
     */
    public ViewSection getSearch() {
        return search;
    }

    /**
     * Sets the value of the search property.
     * 
     * @param value
     *     allowed object is
     *     {@link ViewSection }
     *     
     */
    public void setSearch(ViewSection value) {
        this.search = value;
    }

    /**
     * Gets the value of the orders property.
     * 
     * @return
     *     possible object is
     *     {@link OrdersType }
     *     
     */
    public OrdersType getOrders() {
        return orders;
    }

    /**
     * Sets the value of the orders property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrdersType }
     *     
     */
    public void setOrders(OrdersType value) {
        this.orders = value;
    }

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link Screen.Result }
     *     
     */
    public Screen.Result getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link Screen.Result }
     *     
     */
    public void setResult(Screen.Result value) {
        this.result = value;
    }

    /**
     * Gets the value of the display property.
     * 
     * @return
     *     possible object is
     *     {@link Screen.Display }
     *     
     */
    public Screen.Display getDisplay() {
        return display;
    }

    /**
     * Sets the value of the display property.
     * 
     * @param value
     *     allowed object is
     *     {@link Screen.Display }
     *     
     */
    public void setDisplay(Screen.Display value) {
        this.display = value;
    }

    /**
     * Gets the value of the navigations property.
     * 
     * @return
     *     possible object is
     *     {@link NavigationsType }
     *     
     */
    public NavigationsType getNavigations() {
        return navigations;
    }

    /**
     * Sets the value of the navigations property.
     * 
     * @param value
     *     allowed object is
     *     {@link NavigationsType }
     *     
     */
    public void setNavigations(NavigationsType value) {
        this.navigations = value;
    }

    /**
     * Gets the value of the entity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntity() {
        return entity;
    }

    /**
     * Sets the value of the entity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntity(String value) {
        this.entity = value;
    }

    /**
     * Gets the value of the example property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExample() {
        return example;
    }

    /**
     * Sets the value of the example property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExample(String value) {
        this.example = value;
    }

    /**
     * Gets the value of the softDelete property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean getSoftDelete() {
        if (softDelete == null) {
            return false;
        } else {
            return softDelete;
        }
    }

    /**
     * Sets the value of the softDelete property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSoftDelete(Boolean value) {
        this.softDelete = value;
    }

    /**
     * Gets the value of the canDelete property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean getCanDelete() {
        if (canDelete == null) {
            return true;
        } else {
            return canDelete;
        }
    }

    /**
     * Sets the value of the canDelete property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCanDelete(Boolean value) {
        this.canDelete = value;
    }

    /**
     * Gets the value of the canSave property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean getCanSave() {
        if (canSave == null) {
            return true;
        } else {
            return canSave;
        }
    }

    /**
     * Sets the value of the canSave property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCanSave(Boolean value) {
        this.canSave = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.mda.quintans.pt}viewSection">
     *       &lt;attribute name="embeded" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Display
        extends ViewSection
    {

        @XmlAttribute
        protected Boolean embeded;

        /**
         * Gets the value of the embeded property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean getEmbeded() {
            if (embeded == null) {
                return false;
            } else {
                return embeded;
            }
        }

        /**
         * Sets the value of the embeded property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setEmbeded(Boolean value) {
            this.embeded = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.mda.quintans.pt}viewSection">
     *       &lt;attribute name="target" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Head
        extends ViewSection
    {

        @XmlAttribute(required = true)
        @XmlSchemaType(name = "anySimpleType")
        protected String target;

        /**
         * Gets the value of the target property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTarget() {
            return target;
        }

        /**
         * Sets the value of the target property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTarget(String value) {
            this.target = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.mda.quintans.pt}viewSection">
     *       &lt;attribute name="pageSize" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="selectable" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *       &lt;attribute name="sortable" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Result
        extends ViewSection
    {

        @XmlAttribute
        protected Integer pageSize;
        @XmlAttribute
        protected Boolean selectable;
        @XmlAttribute
        protected Boolean sortable;

        /**
         * Gets the value of the pageSize property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getPageSize() {
            return pageSize;
        }

        /**
         * Sets the value of the pageSize property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setPageSize(Integer value) {
            this.pageSize = value;
        }

        /**
         * Gets the value of the selectable property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean getSelectable() {
            if (selectable == null) {
                return false;
            } else {
                return selectable;
            }
        }

        /**
         * Sets the value of the selectable property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setSelectable(Boolean value) {
            this.selectable = value;
        }

        /**
         * Gets the value of the sortable property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean getSortable() {
            if (sortable == null) {
                return true;
            } else {
                return sortable;
            }
        }

        /**
         * Sets the value of the sortable property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setSortable(Boolean value) {
            this.sortable = value;
        }

    }

}
