//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.10 at 12:26:33 PM WET 
//


package pt.quintans.mda.raw.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import pt.quintans.mda.core.ElementType;


/**
 * <p>Java class for SimpleAssociationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SimpleAssociationType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.mda.quintans.pt}BaseAssociationType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="relation" type="{http://www.mda.quintans.pt}RelationType" minOccurs="0"/>
 *         &lt;element name="constraint" type="{http://www.mda.quintans.pt}ConstraintType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimpleAssociationType", propOrder = {
    "relationAndConstraint"
})
@XmlSeeAlso({
    HasManyType.class,
    HasOneType.class
})
public class SimpleAssociationType
    extends BaseAssociationType
{

    @XmlElements({
        @XmlElement(name = "relation", type = RelationType.class),
        @XmlElement(name = "constraint", type = ConstraintType.class)
    })
    protected List<ElementType> relationAndConstraint;

    /**
     * Gets the value of the relationAndConstraint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relationAndConstraint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelationAndConstraint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelationType }
     * {@link ConstraintType }
     * 
     * 
     */
    public List<ElementType> getRelationAndConstraint() {
        if (relationAndConstraint == null) {
            relationAndConstraint = new ArrayList<ElementType>();
        }
        return this.relationAndConstraint;
    }

}
